channels:
  - name: "HitWest Nantes"
    url: https://stream.rcs.revma.com/42hpctu59k3vv
    start: 2025-04-15 08:00:00 +2
    stop: 2025-04-15 13:00:00 +2
  - name: "HitWest Rennes"
    url: https://stream.rcs.revma.com/nvsuedfwcy3vv
    start: 2025-04-15 08:00:00 +2
    stop: 2025-04-15 13:00:00 +2
  - name: "Radio Classique"
    url: https://str0.creacast.com/classique1
  - name: "France Inter"
    url: http://direct.franceinter.fr/live/franceinter-hifi.aac
    start: 2025-04-12 08:00:00 +2
    stop: 2025-04-18 12:00:00 +2
  - name: "RTL"
    url: http://streaming.radio.rtl.fr/rtl-1-44-128
  - name: "BFM Business"
    url: http://audio.bfmtv.com/bfmbusiness_128.mp3?aw_0_1st.playerId=BFMBusiness_audio_web&aggregator=BFMBusiness_audio_web
  - name: "RMC FR"
    url: https://audio.bfmtv.com/rmcradio_128.mp3
  - name: "France Info"
    url: http://direct.franceinfo.fr/live/franceinfo-hifi.aac
  - name: "Europe 1"
    url: http://stream.europe1.fr/europe1.aac
  - name: "France Bleu Azur"
    url: http://direct.francebleu.fr/live/fbazur-midfi.mp3
  - name: "France Culture"
    url: http://icecast.radiofrance.fr/franceculture-hifi.aac
    start: 2025-04-12 09:00:00 +2
    stop: 2025-04-12 12:00:00 +2
  - name: "Nouvelle-Calédonie La Première"
    url: https://nouvelle-caledonie.ice.infomaniak.ch/nouvelle-caledonie-128.mp3
    start: 2025-04-12 08:00:00 +11
    stop: 2025-04-12 12:00:00 +11
